name = "smallaviationmonitor-api"
main = "src/index.ts"
compatibility_date = "2025-10-15"
compatibility_flags = ["nodejs_compat"]

# Account ID
account_id = "1121916dc461e5864bcb2da2fbfc351e"

# Workers configuration
workers_dev = true

# Routes for production
# routes = [
#   { pattern = "smallaviationmonitor.com/api/*", zone_name = "smallaviationmonitor.com" }
# ]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "smallaviationmonitor-db"
database_id = "dfb0f9f1-0e39-4641-8068-487ef508a278"

# Queue bindings for alerts (requires Workers Paid plan)
# Alternative: Store alerts in D1 and process via scheduled worker
# [[queues.producers]]
# binding = "ALERT_QUEUE"
# queue = "smallaviationmonitor-alerts"

# [[queues.consumers]]
# queue = "smallaviationmonitor-alerts"
# max_batch_size = 10
# max_batch_timeout = 30

# Durable Objects for WebSocket (requires Workers Paid plan)
# Alternative: Use polling or Server-Sent Events for real-time updates on free tier
# [[durable_objects.bindings]]
# name = "WEBSOCKET_COORDINATOR"
# class_name = "WebSocketCoordinator"
# script_name = "smallaviationmonitor-api"

# [[migrations]]
# tag = "v1"
# new_classes = ["WebSocketCoordinator"]

# Environment variables
[env.production]
name = "smallaviationmonitor-api"

[env.production.vars]
ENVIRONMENT = "production"

[env.staging]
name = "smallaviationmonitor-api-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

# Build configuration
# Build configuration will be added when implementing workers
# [build]
# command = "npm run build"
